---
gems:
  - jekyll-default-layout
  - jekyll-theme-tactile
google_analytics: UA-43267418-1
highlighter: rouge
lsi: false
permalink: pretty
safe: true
theme: jekyll-theme-tactile
title: Victor Koronen
